apiVersion: v1
kind: Service
metadata:
  name: {{ include "radarr.fullname" . }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "radarr.selectorLabels" . | nindent 4 }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "radarr.fullname" . }}-metrics
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.exporter.env.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "radarr.selectorLabels" . | nindent 4 }}
{{- end }}