apiVersion: v2
name: radarr
description: A fork of Sonarr to work with movies Ã  la Couchpotato
type: application
version: 1.0.0
appVersion: "6.0.4.10291"
keywords:
  - radarr
  - movies
  - torrent
  - usenet
  - download
home: https://radarr.video/
icon: https://raw.githubusercontent.com/Radarr/Radarr/develop/Logo/256.png
sources:
  - https://github.com/Radarr/Radarr
  - https://github.com/linuxserver/docker-radarr
maintainers:
  - name: jespernohr
    email: ""